'use strict'
var MY_SLACK_WEBHOOK_URL = 'https://myaccountname.slack.com/services/hooks/incoming-webhook?token=myToken';
MY_SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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";
var slack = require('slack-notify')(MY_SLACK_WEBHOOK_URL);
// Bundled notification types:

slack.bug('Something bad happened!'); // Posts to #bugs by default
slack.success('Something good happened!'); // Posts to #alerts by default
slack.alert('Something important happened!'); // Posts to #alerts by default
slack.note('Here is a note.'); // Posts to #alerts by default

const Sendmsg = () => {
    debugger
    // Send custom fields which are nicely displayed by the Slack client:

    slack.alert({
        text: 'Current server stats',
        fields: {
            'CPU usage': '7.51%',
            'Memory usage': '254mb'
        }
    });

    // The `fields` object is custom shorthand for the `attachments` array:

    slack.alert({
        text: 'Current server stats',
        attachments: [{
            fallback: 'Required Fallback String',
            fields: [
                { title: 'CPU usage', value: '7.51%', short: true },
                { title: 'Memory usage', value: '254mb', short: true }
            ]
        }]
    });

    // Everything is overridable:
    var ch = '#Sankar'
    slack.send({
        channel: ch,
        icon_url: '',
        text: 'Hello This msg is generated code through',
        unfurl_links: 1,
        username: 'Kaushik Webashlar'
    });

    // Roll your own notification type:

    var statLog = slack.extend({
        channel: ch,
        icon_emoji: ':computer:',
        username: 'Statistics'
    });

    statLog({
        text: 'This Generated by system by Kaushik Radadya',
        fields: {
            'CPU usage': '7.51%',
            'Memory usage': '254mb'
        }
    });

    // Callbacks and a generic onError function are supported:

    slack.alert('Hello', function(err) {
        if (err) {
            console.log('API error:', err);
        } else {
            console.log('Message received!');
        }
    });

    slack.onError = function(err) {
        console.log('API error:', err);
    };
    //return Tests.findAll();
}


module.exports = {
    Sendmsg
}